### PR TITLE
Refactor E2E by using shared methods.

### PR DESCRIPTION
**Pull request by lalon4**
Also due to a defect, removed the DNS setup step in order to properly test the DNS validation. ClusterPreperation renamed to better represent its purpose

### CODE REVIEW

**Comment by ukalifon** [comment]
/lgtm
however, in the future we'll want to refactor it again so that the shared functions won't be hard-coded to use the environment variables, and will also be reusable when writing non-e2e scripts

**Comment by lalon4** [comment]
Added parameters to shared methods

**Review by jtomasek — CHANGES_REQUESTED** [review]
Please use short summary as a first line of the commit message. Then separate the commit description with a blank line. (More details e.g. here https://chris.beams.io/posts/git-commit/#seven-rules)

**Comment by lalon4** [comment]
Fixed commit message, re based, and aligned ui changes to the flows.
All were ran locally and passed.

**Comment by lalon4** [comment]
Created new PR

**Pull request closed without merging**
