### PR TITLE
Raz/MGMT-1231

### PR DESCRIPTION
**Pull request by RazRegev**
If user pass namespace argument update the default inventory-url to use bm-inventory under this namespace.

### CODE REVIEW

**Comment by mareklibra** [comment]
Thank you for your patch. Honestly, I like approach from #258 most.

Next time you can try `git push --force` to your branch when a PR is open here. Just prefix the PR title with `WIP` to avoid any confusions while you keep working on it.

**Comment by RazRegev** [comment]
> Thank you for your patch. Honestly, I like approach from #258 most.
> 
> Next time you can try `git push --force` to your branch when a PR is open here. Just prefix the PR title with `WIP` to avoid any confusions while you keep working on it.

Right, will do next time. 
Why would you like #258 more then this one?
I think that it is more organized like this but I can also reopen #258

**Comment by mareklibra** [comment]
> Why would you like #258 more then this one?

Code-style reasons only. Two people, two opinions. In that case the function is never called twice and there is expectation that this won't change. The logic fits one line only. It is called directly from already "more" complex command decreasing readability. If you use the simple setting of env variable, the code readability is increased - a future maintainer will not need to "jump" but just read the script from top to bottom.

**Comment by RazRegev** [comment]
> > Why would you like #258 more then this one?
> 
> Code-style reasons only. Two people, two opinions. In that case the function is never called twice and there is expectation that this won't change. The logic fits one line only. It is called directly from already "more" complex command decreasing readability. If you use the simple setting of env variable, the code readability is increased - a future maintainer will not need to "jump" but just read the script from top to bottom.

Legit, fixed that.

**Comment by mareklibra** [comment]
Thanks!

**Pull request merged**
