### PR TITLE
Allow copy&paste of the /etc/hosts hint

### PR DESCRIPTION
**Pull request by mareklibra**
Follow-up for #180

### CODE REVIEW

**Comment by mareklibra** [comment]
---

**Comment by mareklibra** [comment]
@andybraren , what about aligning the icons for these two links to the same side?

**Comment by mareklibra** [comment]
I have added more records to the list

**Comment by jtomasek** [comment]
The text in the popover overflows. We'll need to set overflow to `<pre>` or how about just ditching the popover and open the ConsoleModal? IMHO it would make the experience a bit more unified. WDYT?

Screenshot 2020-06-09 at 15 19 22

**Comment by andybraren** [comment]
Yep, that's a lot of content, time for a modal. 🙂

> @andybraren , what about aligning the icons for these two links to the same side?

I agree it looks a little odd, but external link icons on the right and info icons on the left is the PatternFly [pattern](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/embedded-assistance).

If we change the external link icon to be `fa-external-link-alt` available in the (brand new!) [Icons page](https://www.patternfly.org/v4/design-guidelines/styles/icons#all-icons) it should look less heavy:

image

**Comment by mareklibra** [comment]
I moved the hint into modal and replaced `<pre>` by simple `<div>` for the content to allow reasonable wrapping on smaller displays. Copy&paste still works nice (means: with the correct line separators).

**Pull request merged**
